### ISSUE TITLE
La suscripción debe incluir un campo específico por cada comunidad.

### ISSUE THREAD

**Issue by amartingu72** [amartingu72/greco#17]
Un miembro puede requerir enviar información concreta de cada comunidad donde se suscriba. Esta información será visible desde la página de suscripción de la consola de administración.

**Comment by amartingu72** [comment]
Nos quedamos en subscribeme.xml, programando el tab.

He conseguido un botón siguiente en el primer paso que me redirija al siguiente tab. Habrá que validar en correo haciendo un submit solo de este y dejando lo que venga en el paso 2 sin validar.

**Comment by NuriaMaO** [comment]
Voy a empezar hoy.
